import express from "express";

const app = express();
const PORT = process.env.PORT ?? 3001;

app.use(express.json());

/**
 * ZeroDeploy — AI-powered GitHub repo code review tool.
 *
 * Stack:
 *   - Frontend: generated by Vercel v0 (AI code gen)
 *   - Backend: AWS serverless databases (Zero Stack = zero config)
 *
 * Flow: take a GitHub repo URL -> clone/fetch -> analyze via AI -> quality score.
 *
 * This is the scaffold entrypoint. Real review logic lands in src/review/.
 */

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "zerodeploy",
    version: "0.1.0",
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  });
});

app.get("/", (_req, res) => {
  res.json({
    name: "ZeroDeploy",
    description: "AI-powered GitHub repo code review tool",
    endpoints: {
      health: "GET /health",
    },
  });
});

app.listen(PORT, () => {
  console.log(`🚀 ZeroDeploy API listening on http://localhost:${PORT}`);
});

export default app;
